<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(NetStandardVersion);$(NetVersion)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Akka.Persistence.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Akka.Persistence.Redis\Akka.Persistence.Redis.csproj" />
  </ItemGroup>
</Project>
