<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(NetStandardVersion);$(NetVersion)</TargetFrameworks>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Akka.Persistence.Hosting" />
    <PackageReference Include="Microsoft.Azure.StackExchangeRedis" />
    <PackageReference Include="Azure.Identity" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Akka.Persistence.Redis\Akka.Persistence.Redis.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Akka.Persistence.Redis.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
